"""
Whisper Word-Level Transcription Script
=======================================
Transcribes an audio file using OpenAI Whisper and outputs
word-level timestamps as a JavaScript data file for the
synced lyrics web app.

Usage:
    python transcribe.py <audio_file>

Output:
    lyrics_data.js — word timestamps ready for app.js
"""

import sys
import os
import json

def main():
    if len(sys.argv) < 2:
        print("Usage: python transcribe.py <audio_file>")
        print("Example: python transcribe.py clip.mp3")
        sys.exit(1)

    audio_path = sys.argv[1]

    if not os.path.exists(audio_path):
        print(f"Error: File '{audio_path}' not found")
        sys.exit(1)

    print(f"🎵 Loading audio: {audio_path}")
    print("📦 Loading Whisper model (this may take a moment on first run)...")

    import whisper

    # Use 'base' model for speed, 'small' or 'medium' for accuracy
    # Options: tiny, base, small, medium, large
    model_size = "base"
    print(f"🤖 Using model: {model_size}")
    model = whisper.load_model(model_size)

    print("🔍 Transcribing with word-level timestamps...")
    result = model.transcribe(
        audio_path,
        language="en",
        word_timestamps=True,
        verbose=False
    )

    # Extract word-level data
    words = []
    for segment in result["segments"]:
        if "words" in segment:
            for w in segment["words"]:
                words.append({
                    "word": w["word"].strip(),
                    "start": round(w["start"], 2),
                    "end": round(w["end"], 2)
                })

    if not words:
        print("❌ No words detected in the audio!")
        sys.exit(1)

    print(f"✅ Detected {len(words)} words")
    print()

    # Print detected words with timestamps
    print("─── Detected Words ───")
    for w in words:
        print(f"  [{w['start']:>6.2f}s - {w['end']:>6.2f}s]  {w['word']}")
    print()

    # Group words into lines (by segment)
    lines = []
    for segment in result["segments"]:
        line_text = segment["text"].strip()
        line_start = round(segment["start"], 2)
        line_words = []
        if "words" in segment:
            for w in segment["words"]:
                line_words.append({
                    "word": w["word"].strip(),
                    "time": round(w["start"], 2)
                })
        lines.append({
            "text": line_text,
            "start": line_start,
            "words": line_words
        })

    # Generate JavaScript output
    js_words = json.dumps(
        [{"word": w["word"], "time": w["start"]} for w in words],
        indent=2,
        ensure_ascii=False
    )

    js_content = f"""/**
 * Auto-generated by Whisper transcription
 * Audio: {os.path.basename(audio_path)}
 * Model: {model_size}
 * Words: {len(words)}
 */

window.whisperLyrics = {js_words};
"""

    output_path = os.path.join(os.path.dirname(os.path.abspath(audio_path)), "lyrics_data.js")
    # If audio is in current dir, save next to the script
    if not os.path.dirname(audio_path):
        output_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "lyrics_data.js")

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(js_content)

    print(f"📁 Saved to: {output_path}")
    print()
    print("─── Full Transcription ───")
    print(result["text"].strip())
    print()
    print("✨ Done! The web app will automatically load and use lyrics_data.js when refreshed.")

if __name__ == "__main__":
    main()
